server:
    port: 7001
aws:
  accessKey: AKIA32E6HVBN2X2PUJ7H
  secretKey: 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
  region: us-east-2
  sqsQueue: sha-messagebroker-appB
  endpoint: https://sqs.us-east-2.amazonaws.com/812080670811/sha-messagebroker-appA
activeMQ:
  brokerURL: tcp://localhost:61616
  uname: admin
  password: admin
  queueName: sha-messagebroker-appA
spring:
    activemq:
        in-memory: false
        packages:
            trust-all: true
    autoconfigure:
      exclude:
      -   org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      -   org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
