server:
    port: 7001
aws:
  accessKey: AKIA55C6QLOZO62NMJP3
  secretKey: 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
  region: ap_south_1
  sqsQueue: sha-messagebroker-appB
  endpoint: https://sqs.ap-south-1.amazonaws.com/955828427698/sha-messagebroker-appA
activeMQ:
  brokerURL: tcp://localhost:61616
  uname: admin
  password: admin
  queueName: sha-messagebroker-appA
spring:
    activemq:
        in-memory: false
        packages:
            trust-all: true
    autoconfigure:
      exclude:
      -   org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      -   org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
