spring:
    jms:
      servicebus:
        connection-string: Endpoint=sb://living-goods-service-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=e7TD4p5jcSlkpt9ozmj9UO/UYsrpj231wPAC0tJXyuA=
    autoconfigure:
      exclude:
      -   org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      -   org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
azure:
  queueName: living-goods-queue
server:
  port: 8081
